name: 'Install chef'
description: 'Install chef workstation'
# inputs:
#   who-to-greet:  # id of input
#     description: 'Who to greet'
#     required: true
#     default: 'World'
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/goodbye.sh
      shell: bash
