on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Chef workstation installation
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: zelaskov/chef-test-repo@v1
      - run: ./goodbye.sh
        shell: bash        
