on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Chef workstation installation
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: zelaskov/chef-test-repo@main
        with:
          version: "21.2.278"
